# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 08:21
from __future__ import unicode_literals

from django.db import migrations
from hashlib import sha1

def hash_passwrds(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model('registration', 'Person')
    for person in Person.objects.all():
        person.password = sha1(person.password).hexdigest()
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(hash_passwrds),
    ]
