# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('operation', models.CharField(choices=[('add', 'Add'), ('substract', 'Substract')], max_length=20)),
                ('result', models.FloatField()),
            ],
        ),
    ]
